torchrun --nproc_per_node=4 --master_port=3895 fastchat/train/train.py \
    --model_name_or_path /data2/mfx/huggingface/Llama-2-7b-chat-hf  \
    --data_path /home/txj/datasets/FOLIO/data/train_ft.json \
    --bf16 True \
    --output_dir /home/txj/ft_models/llama2_7b_chat_folio_test \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 100 \
    --save_total_limit 8 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.04 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap offload" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --tf32 True \
    --model_max_length 4096 \
    --gradient_checkpointing True \
    --lazy_preprocess True

